### PR TITLE
call `addOuterRef` only once decl. of outer resolved

### LINKED ISSUE #1787: precondition failure in `applyTypePars`
Applying the following diff (which may not be a sensible idea, but I happened to come across this):
```
diff --git a/lib/String.fz b/lib/String.fz
index f2a89f03..1e9b5b6c 100644
--- a/lib/String.fz
+++ b/lib/String.fz
@@ -525,7 +525,7 @@ public String ref : property.equatable, property.hashable, property.orderable is
   #
   # helper feature which unifies the code of the different split features in one
   #
-  private split0(s String, limit option u32, split_after bool) list String
+  private split0(s T, limit option u32, split_after bool) list String
     pre
       !s.is_empty,
       match limit
```
causes the following precondition failure:
```
error 1: java.lang.Error: require-condition5 failed: dev.flang.ast.AbstractType:applyTypePars:616
	at dev.flang.util.ANY.require(ANY.java:160)
	at dev.flang.ast.AbstractType.applyTypePars(AbstractType.java:616)
	at dev.flang.ast.Call.setActualResultType(Call.java:1410)
	at dev.flang.ast.Call.resolveTypes(Call.java:2186)
	at dev.flang.ast.This.resolveTypes(This.java:238)
	at dev.flang.ast.FeatureAndOuter.target(FeatureAndOuter.java:151)
	at dev.flang.ast.Call.loadCalledFeatureUnlessTargetVoid(Call.java:763)
	at dev.flang.ast.Call.resolveTypes(Call.java:2126)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1283)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1275)
	at dev.flang.ast.Call.visit(Call.java:1121)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Match.visit(Match.java:124)
	at dev.flang.ast.Match.visit(Match.java:43)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:309)
	at dev.flang.ast.Feature.visit(Feature.java:1041)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1333)
	at dev.flang.ast.Resolution.resolveTypes(Resolution.java:461)
	at dev.flang.ast.AbstractFeature.resultTypeIfPresent(AbstractFeature.java:994)
	at dev.flang.ast.Call.resolveTypes(Call.java:2182)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1283)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1275)
	at dev.flang.ast.Call.visit(Call.java:1121)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:309)
	at dev.flang.ast.Feature.visit(Feature.java:1041)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1333)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:258)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:181)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:868)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:156)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)
```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
This ensures that free types have been identified and added to the type parameters of the outer feature.

fixes #1787

### CODE REVIEW

File: src/dev/flang/ast/Feature.java [hunk 1]
```diff
@@ -2525,6 +2526,8 @@ public void addOuterRef(Resolution res)
                                 outerRefType,
                                 outerRefName(),
                                 this);
+
+        whenResolvedTypes(()->_outerRef.scheduleForResolution(res));
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/Feature.java:2530]: Not sure why this is necessary?

**Review by fridis — APPROVED** [review]
very nice you found this fix.
