### PR TITLE
Fix handling of calls to boxed values, fix #1313 fix #1296

### LINKED ISSUE #1296: small example with dynamic instance leads to failure in backends/DFA
The example can probably be simplified more.
```
ex =>

  upper_case Map u32 codepoint is
    upper_case(val Map u32 codepoint) is

    (cache upper_case (() -> upper_case (map_of u32 codepoint [
      (u32 97, codepoint 65)]))).val

  upper_case_me =>
    "a"
      .as_codepoint_sequence
      .mapSequence (c -> upper_case[c.val].get c)


  say upper_case_me
```
```
sam@debian ~/n/fuzion (main)$ fz ~/playground/test.fz 

error 1: *** java.lang.Error: check-condition failed: dev.flang.be.interpreter.ValueWithClazz:clazz:90
Call stack:
((ref ordered_map u32 codepoint).entry).val: $FUZION/lib/ordered_map.fz:52:29:
    val => ordered_map.this.vs[i]
----------------------------^
(((ref ordered_map u32 codepoint).index [ ]).ref @1074498477).call: $FUZION/lib/ordered_map.fz:76:46:
                 .map (i -> sortedEntries[i].val)
---------------------------------------------^
(option i32).map codepoint: $FUZION/lib/option.fz:89:26:
    option.this ? v T => f v
-------------------------^
(ref ordered_map u32 codepoint).index [ ]: $FUZION/lib/ordered_map.fz:76:19:
                 .map (i -> sortedEntries[i].val)
------------------^
(ex.upper_case_me.ref #fun0).call: /home/sam/playground/test.fz:12:36:
      .mapSequence (c -> upper_case[c.val].get c)
-----------------------------------^
(((list codepoint).map codepoint).ref @1074366875).head: $FUZION/lib/list.fz:175:19:
          head => f c.head
------------------^
(((ref list codepoint).map String).ref @1074366875).head: $FUZION/lib/list.fz:175:23:
          head => f c.head
----------------------^
(list String).fold: $FUZION/lib/list.fz:210:76:
                                         | c Cons => c.tail.fold (m.op s c.head) m)
---------------------------------------------------------------------------^
(list String).fold: $FUZION/lib/list.fz:202:30:
  redef fold (m Monoid A) => fold m.e m
-----------------------------^
(ref list codepoint).as_string: $FUZION/lib/list.fz:255:35:
    "{(map String x->x.as_string).fold (String.type.concat sep)}"
----------------------------------^
(ref list codepoint).as_string: $FUZION/lib/list.fz:248:8:
    "[{as_string ","}]"
-------^
fuzion.sys.out.print: $FUZION/lib/fuzion/sys/out.fz:31:13:
    write s.as_string.utf8.as_array
------------^
(io.ref defaultPrintToOut).print: $FUZION/lib/io/out.fz:60:26:
  print(s Any) => stdout.print s
-------------------------^
(io.ref defaultPrintToOut).println: $FUZION/lib/io/printEffect.fz:60:5:
    print s
----^
io.out.println: $FUZION/lib/io/printEffect.fz:41:7:
    p.println s
------^
say: $FUZION/lib/say.fz:31:26:
say(s ref Any) => io.out.println s
-------------------------^
ex: /home/sam/playground/test.fz:15:3:
  say upper_case_me
--^



error 2: java.lang.Error: check-condition failed: dev.flang.be.interpreter.ValueWithClazz:clazz:90
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.be.interpreter.ValueWithClazz.clazz(ValueWithClazz.java:90)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:319)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:573)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:451)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:451)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:497)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:648)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:487)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:643)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:296)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:323)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:334)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:370)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:921)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:803)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:227)
	at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:103)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:368)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:727)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```
```
sam@debian ~/n/fuzion (main)$ fz -c ~/playground/test.fz 

$FUZION/lib/ordered_map.fz:75:19: error 1: NYI: in (ref ordered_map u32 codepoint).index [ ] no targets for Call to (sorted_array ((ref ordered_map u32 codepoint).entry)).find target sorted_array ((ordered_map u32 codepoint).entry)
    sortedEntries.find (e -> ks[e.i] ⋄ k)
------------------^

one error.
sam@debian ~/n/fuzion (main)1$ 
```
```
sam@debian ~/n/fuzion (main)1$ fz -c -Xdfa=off ~/playground/test.fz 
ex.c:135467:39: error: assigning to 'fzT__L58862sorted_u___o_entry_D' (aka 'struct fzT__L58862sorted_u___o_entry_D') from incompatible type 'fzT__L58852sorted_u___o_entry_D' (aka 'struct fzT__L58852sorted_u___o_entry_D')
    fzCur->fields.fzF_2_sortedEntries = fzM_5;
                                      ^ ~~~~~
1 error generated.

error 1: C backend: C compiler failed
C compiler call 'clang -Wall -Werror -Wno-gnu-empty-struct -Wno-unused-variable -Wno-unused-label -Wno-unused-but-set-variable -Wno-unused-function -Wno-infinite-recursion -O3 -lm -lpthread -o ex ex.c' failed with exit code '1'

one error.
```

### LINKED ISSUE #1313: idiom8ex.fz causes NYI error
```
PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -c fuzion-idioms/src/idiom8ex.fz

$FUZION/lib/ordered_map.fz:75:19: error 1: NYI: in (ref ordered_map String i32).index [ ] no targets for Call to (sorted_array ((ref ordered_map String i32).entry)).find target sorted_array ((ordered_map String i32).entry)
    sortedEntries.find (e -> ks[e.i] ⋄ k)
------------------^

one error.

```

### PR DESCRIPTION
**Pull request by fridis**
### Boxed value handling

Boxed values created from a value instance by assigning it to a compatible ref type are now different to ref types as follows: A boxed type is seen as a value type that was wrapped together with a type identitifier into a heap object.
    
The main problem that was solved is the use of `t.this.type` within a value type `t`. If an instance of `t` was boxed and became and instance of type `ref t`, uses of `t`, e.g., as the outer type of types defined within `t`'s inner features would become `ref t` resulting in incompatibilities as shown in #1313.
    
The solution taken is that a boxed instance of `t` is of type `ref t`, but contains a copy of the original value instance of type `t`.  Any access that is made to the boxed value is then made on this copied value instance, so internally `t.this.type` is still `t`.
    
The most important change this implies is that on a dynamically bound access to a feature (e.g., a call `r.f` on a reference `r`), if the actual value of `r` is some boxed value type `v`, `f` will be called on this value type and not on the corresonding boxed type `ref v` (except for for precondtions and constructors described below).
    
This change required some (partially unexpected) preliminary work that is part of this commit:
    
- dynamic binding is now permitted for features with type parameters.
 
  For this to be possible, the code for dynamic feature lookup (Clazz.lookup) had to be extended to not look up a given feature, but to lookup a feature combined with its type parameters.  A new class FeatureAndActuals was added for this.
    
- constructors require special handling since they create new values whose type is the type defined by the constructor with the outer type defined by the target of the call.
    
  A call `t.c` hence creates an instance of `T.c` where `T` is the type of `t`. If `t` is a ref type and the actual value is a boxed value type `v` that inherits from `T`, we cannot call `c` on that value instance since the outer type must be `T`. Consequently, constructors when called on a `ref` target that is a boxed value type will be called on the boxed value, their outer type is a `ref` type. The result type of a call to a constructor `t1.c` is hence different to the result of a call to `t2.c` if `t1` is a value type `v` and `t2` is a ref type and the actual instance is the corresponding boxed type `ref v`.
    
- preconditions require special handling since preconditions do not use dynamic binding, but static binding.
    
  If the static type of the target `t` of a call `t.f` is a boxed type `ref v` and `f` has a precondition, it is not possible to call the precondition on the target type `v` since `t` might refer to an instance of type `w` that inherits from `v`.
    
  So instead, preconditions may be called on boxed types, in this case the precondition will be called on static type `ref v`, while `f` will be called on the value type `v` or a different actual type the value `t` refers to.
    
  Due to the potential difference in target types for calls to preconditions, the code for call target lookup had to be change to take care for this.  A flag was added to FeatureAndActuals to handle preconditions.
    
- DFA could be simplified and no longer needs to determine value instances from ref clazzes.
    
- The front end no longer needs the distinction between dynamic and static calls, AbstractFeature.isDynamic() was removed.
    
One change to the base lib was needed: `CTrie.not_found` had to be moved out of `CTrie` since the type of `not_foound` when used within `CTrie` is `CTrie.this.type.not_found`, which results in different and incompatible types for different possible heirs of `CTrie`.
    
### New errors were introduced:
    
- outerTypeMayNotBeRefType: It is now forbidden to use `ref t` as the outer type in source code, e.g., `x (ref t).v := y` is not possible.
    
- illegalCallResultType: A call `a.f` whose target type is a boxed type `ref v` is forbiddent if the result type of `f`depends on the actual outer type `a.this.type`. The reason is that in case 'a' is a different type that inherits from 'a', the resulting type would be incomptible.
     
- illegalOuterRefTypeINcall: Similarly, A call `a.f` whose result type depends on the actual outer type `a.this.type` is forbidden if `a` is a `ref` type. The reason is that in case 'a''s actual value is a (boxed value) type that inherits from 'a', the resulting type would be incomptible.

### Tests

Added tests for calls on boxed values
    
Also added negative tests for
    
- AstErrors.illegalCallResultType,
- AstErrors.illegalOuterRefTypeInCall, and
- AstErrors.outerTypeMayNotBeRefType

various fixes for new handling of boxed value types
    
Due to a bug in the interpreter with mutable data, test `valWithDynOuter` is skipped for the interpreter for now.

### CODE REVIEW

File: src/dev/flang/air/FeatureAndActuals.java [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+import dev.flang.ast.AbstractType; // NYI: remove dependency!
+
+import dev.flang.util.ANY;
+import dev.flang.util.List;
+
+
+/**
+ * FeatureAndActuals represents a triplet consisting of an AbstractFeature
+ * combined with a list of actual type parameters for that feature and a flag
+ * selecting between the feature itself of the precondition of this feature.
```
Comment (michaellilltokiwa) [inline src/dev/flang/air/FeatureAndActuals.java:40]: ...or the precondition...

File: src/dev/flang/air/FeatureAndActuals.java [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+ *
+ * Instances of this are used as the key the the set of inner clazzes in a Clazz
+ * since for this inner clazz to exist, there must be a call iwth actual type
```
Comment (michaellilltokiwa) [inline src/dev/flang/air/FeatureAndActuals.java:43]: iwth -> with

File: src/dev/flang/ast/AbstractCall.java [hunk 3]
```diff
@@ -121,7 +121,6 @@ public void visitStatements(StatementVisitor v)
   public boolean isDynamic()
   {
     return
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/AbstractCall.java:123]: comment above needs to be updated to reflect the change in the code.

File: src/dev/flang/ast/AbstractFeature.java [hunk 4]
```diff
@@ -1140,21 +1140,6 @@ public boolean definesType()
   }
 
 
-  /**
-   * Are calls to this feature performed using dynamic binding?
-   */
-  public boolean isDynamic()
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/AbstractFeature.java:1146]: It makes sense to me intuitively that this is removed since IMHO it should not be for a feature to decide _how_ it is being called.

File: tests/call_with_ambiguous_result_type_negative/Makefile [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+#
+#  Source code of Fuzion test Makefile
+#
+#  Author: Fridftjof Siebert (fridtjof.siebert@tokiwa.software)
+#
+# -----------------------------------------------------------------------
+
+override NAME = call
+
+include ../simple_inp.mk
```
Comment (michaellilltokiwa) [inline tests/call_with_ambiguous_result_type_negative/Makefile:28]: should probably be `simple.mk`

File: tests/calls_on_ref_and_val_target/Makefile [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+#
+#  Source code of Fuzion test Makefile
+#
+#  Author: Fridftjof Siebert (fridtjof.siebert@tokiwa.software)
+#
+# -----------------------------------------------------------------------
+
+override NAME = calls
+
+include ../simple_inp.mk
```
Comment (michaellilltokiwa) [inline tests/calls_on_ref_and_val_target/Makefile:28]: should probably be `simple.mk`

File: tests/calls_on_ref_and_val_target_negative/Makefile [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+#
+#  Source code of Fuzion test Makefile
+#
+#  Author: Fridftjof Siebert (fridtjof.siebert@tokiwa.software)
+#
+# -----------------------------------------------------------------------
+
+override NAME = calls
+
+include ../simple_inp.mk
```
Comment (michaellilltokiwa) [inline tests/calls_on_ref_and_val_target_negative/Makefile:28]: should probably be `simple.mk`

File: src/dev/flang/air/FeatureAndActuals.java [hunk 8]
```diff
@@ -0,0 +1,192 @@
...
+
+    _f = f;
+    _tp = tp;
+    _preconditionClazz = preconditionClazz;
+    _max = false; /* unused */
+    }
+
+
+  /**
+   * Convenience constructor for empty type parameters and not precondition clazz.
```
Comment (michaellilltokiwa) [inline src/dev/flang/air/FeatureAndActuals.java:114]: ... no precondition clazz...

File: src/dev/flang/air/Clazz.java [hunk 9]
```diff
@@ -1069,39 +1087,46 @@ public Clazz lookup(AbstractFeature f,
...
-   * Lookup the code to call the feature f from this clazz using dynamic binding
-   * if needed.
+   * Lookup the code to call given feature with actual type parameters, using
+   * the position returned by Clazzes.isUsedAt(fa._f) as the call position.
    *
    * This is not intended for use at runtime, but during analysis of static
    * types or to fill the virtual call table.
    *
-   * @param f the feature that is called
+   * @param fa the feature and actualt types that is called
```
Comment (michaellilltokiwa) [inline src/dev/flang/air/Clazz.java:1101]: ...actual types...

File: src/dev/flang/air/Clazz.java [hunk 10]
```diff
@@ -1069,39 +1087,46 @@ public Clazz lookup(AbstractFeature f,
...
+
+
+  /**
+   * Lookup the code to call given feature with actual type parameters, using
+   * the given call position or null if not a call.
+   *
+   * This is not intended for use at runtime, but during analysis of static
+   * types or to fill the virtual call table.
+   *
+   * @param fa the feature and actualt types that is called
```
Comment (michaellilltokiwa) [inline src/dev/flang/air/Clazz.java:1118]: actualt -> actual

File: src/dev/flang/fuir/analysis/dfa/ValueSet.java [hunk 11]
```diff
@@ -153,6 +153,22 @@ public Value joinInstances(Value v)
...
+   * Box this value. This works both for Instances as well as for value types
+   * such as i32, bool, etc.
+   */
+  Value box(DFA dfa, int vc, int rc, Context context)
+  {
+    Value result = null;
+    for (var v : _components.values())
+      {
+        var u = v.box(dfa, vc, rc, context);
+        result = result == null ? u : new ValueSet(result, u);
```
Comment (michaellilltokiwa) [inline src/dev/flang/fuir/analysis/dfa/ValueSet.java:166]: This seems greater than O(n) but I think it could be O(n)?
Something like: 
```
_components
  .values()
  .flatMap(v -> v.box(...)._components.values())
 ```

File: src/dev/flang/ast/Call.java [hunk 12]
```diff
@@ -1431,7 +1431,11 @@ private AbstractType adjustThisTypeForTarget(AbstractType t)
       {
         var inner = new Type(calledFeature().selfType(),
                              _target.typeForCallTarget());
-        t = t.replace_this_type_by_actual_outer(inner);
+        var t0 = t;
+        var c = Errors.count();
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/Call.java:1435]: What is the purpose of this `Errors.count()`?

File: src/dev/flang/be/c/C.java [hunk 13]
```diff
@@ -164,11 +164,12 @@ public CStmnt assign(int cl, int c, int i, CExpr tvalue, CExpr avalue)
      */
     public Pair<CExpr, CStmnt> call(int cl, int c, int i, CExpr tvalue, List<CExpr> args)
     {
-      var cc0 = _fuir.accessedClazz  (cl, c, i);
+      var ccP = _fuir.accessedPreconditionClazz(cl, c, i);
+      var cc0 = _fuir.accessedClazz            (cl, c, i);
       var ol = new List<CStmnt>();
-      if (_fuir.hasPrecondition(cc0))
+      if (ccP != -1)
```
Comment (michaellilltokiwa) [inline src/dev/flang/be/c/C.java:170]: _Magic_ number should be put in a constant imho.

File: src/dev/flang/be/c/C.java [hunk 14]
```diff
@@ -872,12 +873,18 @@ Pair<CExpr, CStmnt> access(int cl, int c, int i, CExpr tvalue, List<CExpr> args)
         CStmnt acc = CStmnt.EMPTY;
         for (var cci = 0; cci < ccs.length; cci += 2)
           {
-            var tt = ccs[cci  ];
-            var cc = ccs[cci+1];
+            var tt = ccs[cci  ];                   // target clazz we match against
+            var cc = ccs[cci+1];                   // called clazz in cased of match
```
Comment (michaellilltokiwa) [inline src/dev/flang/be/c/C.java:877]: ... in case of match...

File: src/dev/flang/fuir/FUIR.java [hunk 15]
```diff
@@ -1305,6 +1328,50 @@ public String comment(int cl, int c, int ix)
   }
 
 
+  /**
+   * Get the inner clazz the precondition of a call, -1 if no precondition.
```
Comment (michaellilltokiwa) [inline src/dev/flang/fuir/FUIR.java:1332]: ...the inner clazz of the precondition...

File: src/dev/flang/ast/AbstractType.java [hunk 16]
```diff
@@ -1012,40 +1013,65 @@ public String name()
...
+  }
+
+
   /**
    * Helper for replace_this_type_by_actual_outer to replace `this.type` for
    * exactly tt, ignoring tt.outer().
    *
    * @param tt the type feature we are calling
+   *
+   * @param foundRef a consumer that will be called for all the the this-types
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/AbstractType.java:1054]: the the

File: tests/call_with_ambiguous_result_type_negative/call.fz [hunk 17]
```diff
@@ -0,0 +1,49 @@
...
+  r ref is
+    e is
+
+    # result type of g is r.this.type.e
+    g => e
+
+  h1 : r is
+  h2 : r is
+
+  # v will set to `boxed h1` or `boxed h2`
```
Comment (michaellilltokiwa) [inline tests/call_with_ambiguous_result_type_negative/call.fz:40]: ...will be...

**Review by michaellilltokiwa — APPROVED** [review]

File: src/dev/flang/fuir/analysis/dfa/ValueSet.java (hunk 11 above)
Comment (fridis) [reply src/dev/flang/fuir/analysis/dfa/ValueSet.java:167]: I have added a NYI-comment for now. There are several things in the DFA that have quadratic, maybe even cubic performance, these will have to be solved later. Very likely, the size of ValueSet would be limited to something like 10, which magically turns this code from O(n²) to O(1) since n<=10.

File: src/dev/flang/be/c/C.java (hunk 13 above)
Comment (fridis) [reply src/dev/flang/be/c/C.java:170]: -1 is used at several places to mean 'no class', could be fixed in a separate patch.

File: src/dev/flang/ast/Call.java (hunk 12 above)
Comment (fridis) [reply src/dev/flang/ast/Call.java]: forgotten debug code, removed in my latest update.

File: src/dev/flang/fuir/FUIR.java [hunk 18]
```diff
@@ -1471,7 +1546,7 @@ public boolean accessIsDynamic(int cl, int c, int ix)
       (s instanceof AbstractAssign ass ) ? ((Clazz) outerClazz.getRuntimeData(ass._tid)).isRef() : // NYI: This should be the same as assignedField._outer
       (s instanceof Clazz          arg ) ? outerClazz.isRef() && !arg.feature().isOuterRef() : // assignment to arg field in inherits call (dynamic if outerlClazz is ref)
                                                                                        // or to outer ref field (not dynamic)
-      (s instanceof AbstractCall   call) ? call.isDynamic() && ((Clazz) outerClazz.getRuntimeData(call._sid + 1)).isRef() :
+      (s instanceof AbstractCall   call) ? (true || call.isDynamic()) && ((Clazz) outerClazz.getRuntimeData(call._sid + 1)).isRef() && (true || !call.calledFeature().isConstructor() || !((Clazz) outerClazz.getRuntimeData(call._sid + 1)).isBoxed())  :
```
[the remark this answers is not in the document]
Comment (fridis) [reply src/dev/flang/fuir/FUIR.java]: removed this, was left from debugging.
