### PR TITLE
be/int: fix set casefield in case result type is unittype

### LINKED ISSUE #4281: require-condition1 failed: LValue.java:248 "(size == Layout.get(_clazz).size());"
```
match true
  a false_ => say a
  b true_  => say b
```
```
Error 1: *** java.lang.Error: require-condition1 failed: LValue.java:248 "(size == Layout.get(_clazz).size());"
Call stack:



error 2: java.lang.Error: require-condition1 failed: LValue.java:248 "(size == Layout.get(_clazz).size());"
        at dev.flang.util.ANY.require(ANY.java:101)
        at dev.flang.be.interpreter.LValue.storeNonRef(LValue.java:248)
        at dev.flang.be.interpreter.Interpreter.setNonRefField(Interpreter.java:515)
        at dev.flang.be.interpreter.Interpreter.setFieldSlot(Interpreter.java:483)
        at dev.flang.be.interpreter.Interpreter.setField(Interpreter.java:163)
        at dev.flang.be.interpreter.Executor.match(Executor.java:538)
        at dev.flang.be.interpreter.Executor.match(Executor.java:56)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:656)
        at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:514)
        at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:490)
        at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:87)
        at dev.flang.tools.Fuzion$Backend$1.process(Fuzion.java:108)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:499)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1064)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
        at dev.flang.util.Errors.runAndExit(Errors.java:903)
        at dev.flang.tools.Tool.run(Tool.java:142)
        at dev.flang.tools.Fuzion.main(Fuzion.java:618)


*** fatal errors encountered, stopping.
2 errors.

```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #4281

### CODE REVIEW

File: src/dev/flang/be/interpreter/Executor.java [hunk 1]
```diff
@@ -533,11 +533,11 @@ public Pair<Value, Object> match(int s, AbstractInterpreter<Value, Object> ai, V
     var cix = _fuir.matchCaseIndex(s, tagAndChoiceElement.v0());
 
     var field = _fuir.matchCaseField(s, cix);
-    if (field != -1)
+    if (field != -1 && !_fuir.clazzIsUnitType(_cur.clazz()))
```
Comment (fridis) [inline src/dev/flang/be/interpreter/Executor.java:536]: I think this should work as well and it would work even if `_cur.clazz()` is not a unit type due to some other fields unrelated to the `match`:
```suggestion
    if (field != -1 && !_fuir.clazzIsUnitType(_fuir.clazzResultClazz(field)))
```
