### PR TITLE
fe: show error when lambda types outer(s) contain generic argument

### LINKED ISSUE #6917: lambda outer generic type does not work
```
outer is
  F ref is
    c(a i32) i32 : fuzion.lambda_target => abstract

  d(O type : outer) is

    _ O.F:= x->x+1   # should work, but does not
```
```
error 1: java.lang.Error: require-condition2 failed: AbstractType.java:237 "(!(this instanceof UnresolvedType), !isGenericArgument());"
        at dev.flang.util.ANY.require(ANY.java:156)
        at dev.flang.ast.AbstractType.feature(AbstractType.java:237)
        at dev.flang.ast.Function.targetCalls(Function.java:451)
        at dev.flang.ast.Function.targetCalls(Function.java:461)
        at dev.flang.ast.Function.propagateTypeAndInferResult(Function.java:383)
        at dev.flang.ast.Function.propagateExpectedType(Function.java:208)
        at dev.flang.ast.AbstractAssign.propagateExpectedType(AbstractAssign.java:164)
        at dev.flang.ast.Feature$5.action(Feature.java:2031)
        at dev.flang.ast.AbstractAssign.visit(AbstractAssign.java:128)
        at dev.flang.ast.AbstractAssign.visit(AbstractAssign.java:38)
        at dev.flang.ast.Block.visit(Block.java:220)
        at dev.flang.ast.Block.visit(Block.java:43)
        at dev.flang.ast.Block.visit(Block.java:220)
        at dev.flang.ast.Block.visit(Block.java:43)
        at dev.flang.ast.Impl.visit(Impl.java:303)
        at dev.flang.ast.Feature.visit(Feature.java:1292)
        at dev.flang.ast.Feature.typeInference(Feature.java:2030)
        at dev.flang.ast.Feature.typeInference(Feature.java:2003)
        at dev.flang.ast.Resolution.resolveOne(Resolution.java:459)
        at dev.flang.ast.Resolution.resolve(Resolution.java:410)
        at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:259)
        at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:162)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$0(Fuzion.java:1190)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
        at dev.flang.util.Errors.runAndExit(Errors.java:930)
        at dev.flang.tools.Tool.run(Tool.java:142)
        at dev.flang.tools.Fuzion.main(Fuzion.java:744)
```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes https://github.com/tokiwa-software/fuzion/issues/6917

### CODE REVIEW

File: src/dev/flang/ast/AstErrors.java [hunk 1]
```diff
@@ -2633,6 +2633,21 @@ public static void illegalNumLiteral(ParsedCall c)
...
+  {
+    error(pos, "Can not create lambda since an outer has unkown arguments.",
+      "The outer having the arguments:\n\n" + s_feat_with_pos(tt.feature()) + "\n"+
+      "To solve this, either create the lambda inside of " + s(tt.feature()) + " or remove the arguments from " + s(tt.feature()) + "."
+     );
+  }
+
+  public static void lamdaOuterMustNotBeGenericArgument(SourcePosition pos, AbstractType tt)
+  {
+    error(pos, "Can not create lambda since an outer of its type is a generic argument and we don't now how to create an instance of this.",
```
Comment (maxteufel) [inline src/dev/flang/ast/AstErrors.java]:
```suggestion
    error(pos, "Can not create lambda since an outer of its type is a generic argument and we don't know how to create an instance of this.",
```
typo. However, error messages should not tell stories. The second part of the sentence does not give any more information than just
```suggestion
    error(pos, "Can not create lambda since an outer of its type is a generic argument.",
```

**Review by maxteufel — CHANGES_REQUESTED** [review]
Small nitpick, otherwise good.

**Comment by maxteufel** [comment]
merge incongruence with 6915

**Review by maxteufel — APPROVED** [review]
