### PR TITLE
ast/If: issue 536, default else branch returns `unit`

### LINKED ISSUE #536: `if` statement does not work as expected when a branch returning `unit` type is not explicitly provided
The following code should reproduce the problem:
```
ex =>
  log(a bool) outcome unit is
    if !a
       error "a is false"

  say (log (envir.args.count < 2))
```

When `a` is a constant, both the C backend and the interpreter return an error at compile time but in the aforementioned case it results in a segmentation fault in C be and NullPointerException in the interpreter be.

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #536

### CODE REVIEW

File: src/dev/flang/ast/If.java [hunk 1]
```diff
@@ -354,6 +353,15 @@ If assignToField(Resolution res, AbstractFeature outer, Feature r)
       {
         elseIf = elseIf.assignToField(res, outer, r);
       }
+    // special case, default else-branch returning `unit`:
+    // there is no explicit else-branch but we assign if to a field which
+    // we can assign `unit` to. Thus we generate a default else branch.
+    if(hasUntakenElseBranch() && r.resultType().isAssignableFrom(Types.resolved.t_unit))
```
Comment (fridis) [inline src/dev/flang/ast/If.java:359]: please add space after `if`

File: src/dev/flang/fuir/analysis/Escape.java [hunk 2]
```diff
@@ -97,7 +97,8 @@ public Escape(FUIR fuir)
   public boolean doesCurEscape(int cl)
   {
     if (PRECONDITIONS) require
-      (_fuir.clazzKind(cl) == IR.FeatureKind.Routine);
+      ( _fuir.clazzKind(cl) == IR.FeatureKind.Routine
+      ||_fuir.clazzKind(cl) == IR.FeatureKind.Intrinsic);
```
Comment (fridis) [inline src/dev/flang/fuir/analysis/Escape.java:101]: please add space after `||`

**Review by fridis — COMMENTED** [review]
Looks very good, just very minor formatting nitpicking in my comments. 
Can you update #544 such that I can pull in both PRs at once.
