### PR TITLE
ast: fix resolveFormalArg, when target type is generic argument

### LINKED ISSUE #1919: higher-order constraint yields check-condition failure
```
test =>

  a(T type: (i32) -> float, b T) float is
    b.call

  say (a i32->f64 (x -> 0.23))
```
```
/home/not_synced/fuzion (treiber_stack)1$ fz ~/playground/test.fz 

error 1: java.lang.Error: check-condition failed: dev.flang.ast.ResolvedParametricType:generics:149
        at dev.flang.util.ANY.check(ANY.java:383)
        at dev.flang.ast.ResolvedParametricType.generics(ResolvedParametricType.java:149)
        at dev.flang.ast.Call.resolveFormalArg(Call.java:1281)
        at dev.flang.ast.Call.lambda$resolveFormalArgumentTypes$11(Call.java:1354)
        at dev.flang.ast.AbstractFeature.whenResolvedTypes(AbstractFeature.java:1059)
        at dev.flang.ast.Call.resolveFormalArgumentTypes(Call.java:1354)
        at dev.flang.ast.Call.resolveTypes(Call.java:2213)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1281)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1273)
        at dev.flang.ast.Call.visit(Call.java:1127)
        at dev.flang.ast.Block.visit(Block.java:226)
        at dev.flang.ast.Block.visit(Block.java:40)
        at dev.flang.ast.Impl.visit(Impl.java:314)
        at dev.flang.ast.Feature.visit(Feature.java:1039)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1331)
        at dev.flang.ast.Resolution.resolveTypes(Resolution.java:461)
        at dev.flang.ast.AbstractFeature.resultTypeIfPresent(AbstractFeature.java:993)
        at dev.flang.ast.Call.resolveTypes(Call.java:2194)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1281)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1273)
        at dev.flang.ast.Call.visit(Call.java:1127)
        at dev.flang.ast.Block.visit(Block.java:226)
        at dev.flang.ast.Block.visit(Block.java:40)
        at dev.flang.ast.Resolution.resolveType(Resolution.java:481)
        at dev.flang.ast.Call.lambda$resolveTypesOfActuals$5(Call.java:842)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1347)
        at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
        at dev.flang.ast.Resolution.resolve(Resolution.java:338)
        at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:259)
        at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:183)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:892)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:156)
        at dev.flang.util.Errors.runAndExit(Errors.java:757)
        at dev.flang.tools.Tool.run(Tool.java:156)
        at dev.flang.tools.Fuzion.main(Fuzion.java:543)


*** fatal errors encountered, stopping.
```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #1919

### CODE REVIEW

**Review by fridis — APPROVED** [review]
A minor cleanup suggestion and another one for a new PR. See below.

**Comment by michaellilltokiwa** [comment]
> A minor cleanup suggestion and another one for a new PR. See below.

Where is the suggestion?

File: src/dev/flang/ast/Call.java [hunk 1]
```diff
@@ -1344,7 +1344,9 @@ private void resolveFormalArg(Resolution res, int argnum, AbstractFeature frml,
                 Generic g = frmlT.genericArgument();
                 var frmlTs = g.replaceOpen(g.feature() == _calledFeature
                                            ? _generics
-                                           : _target.type().generics());
+                                           : (heir.isGenericArgument() // see for example #1919
+                                                ? heir.genericArgument().constraint(res, context).generics()
+                                                : heir.generics()));
```
Comment (fridis) [inline src/dev/flang/ast/Call.java:1349]:
```suggestion
                                           : (heir.isGenericArgument() // see for example #1919
                                                ? heir.genericArgument().constraint(res, context)
                                                : heir
                                             ).generics());
```
The pattern `t.isGenericArgument() ? t.genericArgument.constraint(res, context) : t` occurs at several places. Might be good to move this in to a method in `AbstractType`, in a separate PR.
