### PR TITLE
fz_cmd: check for invalid values in provided options

### LINKED ISSUE #4156: fz: handle invalid arguments given on command line
I think this should not happen:
```
$ fz -XmaxErrors=

error 1: java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:672)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at dev.flang.tools.Tool.parseGenericArg(Tool.java:256)
	at dev.flang.tools.Fuzion.parseArgsForBackend(Fuzion.java:926)
	at dev.flang.tools.Fuzion.parseArgs(Fuzion.java:703)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
	at dev.flang.util.Errors.runAndExit(Errors.java:897)
	at dev.flang.tools.Tool.run(Tool.java:142)
	at dev.flang.tools.Fuzion.main(Fuzion.java:600)


*** fatal errors encountered, stopping.
one error.
```

### PR DESCRIPTION
**Pull request by simonvonhackewitz**
fix #4156

examples
```
❯ fz -XmaxErrors -e 'say "ok"' 
ok

❯ fz -XmaxErrors=twenty -e 'say "ok"'

error 1: 'twenty' is not a valid argument to option '-XmaxErrors'. Please provide a integer value or use the option without an argument for unlimited errors.
Usage: /home/simon/fuzion/build/bin/fz [-h|--help|-version]  --or--
       /home/simon/fuzion/build/bin/fz [-c|-classes|-dfa|-effects|-frontend-only|-interpreter|-jar|-java|-jvm|-llvm|-no-backend|-saveLib=<file>] [-h|--help|-version] [<backend specific options>]  --or--
       /home/simon/fuzion/build/bin/fz -pretty [-noANSI] [-verbose[=<n>]]  ({<file>} | - | -e <code> | -execute <code>)  --or--
       /home/simon/fuzion/build/bin/fz -latex [-noANSI] [-verbose[=<n>]]   --or--
       /home/simon/fuzion/build/bin/fz -acemode [-noANSI] [-verbose[=<n>]]   --or--

*** fatal errors encountered, stopping.
one error.

❯ fz -XmaxWarnings=5.0 -e 'say "ok"'

error 1: '5.0' is not a valid argument to option '-XmaxWarnings'. Please provide a integer value or use the option without an argument for unlimited warnings.
Usage: /home/simon/fuzion/build/bin/fz [-h|--help|-version]  --or--
       /home/simon/fuzion/build/bin/fz [-c|-classes|-dfa|-effects|-frontend-only|-interpreter|-jar|-java|-jvm|-llvm|-no-backend|-saveLib=<file>] [-h|--help|-version] [<backend specific options>]  --or--
       /home/simon/fuzion/build/bin/fz -pretty [-noANSI] [-verbose[=<n>]]  ({<file>} | - | -e <code> | -execute <code>)  --or--
       /home/simon/fuzion/build/bin/fz -latex [-noANSI] [-verbose[=<n>]]   --or--
       /home/simon/fuzion/build/bin/fz -acemode [-noANSI] [-verbose[=<n>]]   --or--

*** fatal errors encountered, stopping.
one error.

❯ fz -XjavaProf= -e 'say "ok"'      

error 1: Please provide a file name to option '-XjavaProf=<file>'.
Usage: /home/simon/fuzion/build/bin/fz [-h|--help|-version]  --or--
       /home/simon/fuzion/build/bin/fz [-c|-classes|-dfa|-effects|-frontend-only|-interpreter|-jar|-java|-jvm|-llvm|-no-backend|-saveLib=<file>] [-h|--help|-version] [<backend specific options>]  --or--
       /home/simon/fuzion/build/bin/fz -pretty [-noANSI] [-verbose[=<n>]]  ({<file>} | - | -e <code> | -execute <code>)  --or--
       /home/simon/fuzion/build/bin/fz -latex [-noANSI] [-verbose[=<n>]]   --or--
       /home/simon/fuzion/build/bin/fz -acemode [-noANSI] [-verbose[=<n>]]   --or--

*** fatal errors encountered, stopping.
one error.
```

### CODE REVIEW

File: src/dev/flang/tools/Tool.java [hunk 1]
```diff
@@ -249,15 +249,37 @@ else if (a.equals("-XjavaProf"))
...
+    else if (a.equals(Errors.MAX_ERROR_MESSAGES_OPTION))
       {
-        Errors.MAX_ERROR_MESSAGES = Integer.parseInt(a.substring(a.indexOf("=")+1));
+        Errors.MAX_ERROR_MESSAGES = -1;
       }
-    else if (a.startsWith(Errors.MAX_WARNING_MESSAGES_OPTION) && a.startsWith(Errors.MAX_WARNING_MESSAGES_OPTION + "="))
+    else if (a.startsWith(Errors.MAX_ERROR_MESSAGES_OPTION + "="))
       {
-        Errors.MAX_WARNING_MESSAGES = Integer.parseInt(a.substring(a.indexOf("=")+1));
+        try {
```
Comment (michaellilltokiwa) [inline src/dev/flang/tools/Tool.java:264]: why not use parsePositiveIntArg?

Comment (simonvonhackewitz) [reply src/dev/flang/tools/Tool.java:264]: to keep the possibility to set it to `=-1` for unlimited errors. Do you think it would be better to remove that?

Comment (michaellilltokiwa) [reply src/dev/flang/tools/Tool.java:264]: parsePositiveIntArg is misleading it also parses negative numbers. Please rename.

**Review by michaellilltokiwa — APPROVED** [review]
