### PR TITLE
Complete rewrite of handling of outer types, fix #1180, fix #229

### LINKED ISSUE #229: C backend: invalid code generated for `tests/valWithDynOuter/valWithDynOuter.fz`
commit bb964b651c968a5d40f8786aa4c4cc7ca55b08e1

```
$ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1, mixed mode, sharing)
$ make
[...]
$ make run_tests
testing interpreter: ............._..............._..................._......_ 53/57 tests passed, 4 skipped, 0 failed.
testing C backend: ........._..._.........._...._..................._...#.._ 50/57 tests passed, 6 skipped, 1 failed.
./build/tests/valWithDynOuter/: failed
make: [Makefile:364: run_tests_c] Error 1 (ignored)
```

Reproduce:

```
$ cd build/tests/valWithDynOuter/
$ ../../bin/fz valWithDynOuter.fz
PASSED: .v1-v:v.x.
PASSED: .w-w:w.x.
PASSED: .v2-v:v.x.
PASSED: .w-w:w.x.
PASSED: .s-s:s.x.
PASSED: .v1-v:v.x.
PASSED: .w-w:w.x.
PASSED: .v2-v:v.x.
PASSED: .w-w:w.x.
PASSED: .s-s:s.x.
PASSED: v1
PASSED: .v1v1-v:v.x.
PASSED: v1v1
PASSED: w
PASSED: .ww-w:w.x.
PASSED: ww
PASSED: v2
PASSED: .v2v2-v:v.x.
PASSED: v2v2
PASSED: w
PASSED: .ww-w:w.x.
PASSED: ww
PASSED: s
PASSED: .ss-s:s.x.
PASSED: ss
$ ../../bin/fz -c valWithDynOuter.fz
valWithDynOuter.c:37300:23: error: assigning to 'fzT_valWithDynOuter__1v__e' (aka 'struct fzT_valWithDynOuter__1v__e') from incompatible type 'fzT_valWithDynOuter__w__e' (aka 'struct fzT_valWithDynOuter__w__e')
  fzCur->fzF_1_result = fzM_1;
                      ^ ~~~~~
[...]
12 errors generated.

error 1: C backend: C compiler failed
C compiler call 'clang -O3 -lm -o valWithDynOuter valWithDynOuter.c' failed with exit code '1'

one error.
$ clang --version | head -n 1
Debian clang version 13.0.1-3+b1
```

GCC fails similarly:

```
$ gcc valWithDynOuter.c
valWithDynOuter.c: In function ‘fzC_valWithDynOuter__q2’:
valWithDynOuter.c:37300:25: error: incompatible types when assigning to type ‘fzT_valWithDynOuter__1v__e’ from type ‘fzT_valWithDynOuter__w__e’
37300 |   fzCur->fzF_1_result = fzM_1;
      |                         ^~~~~
[...]
$ gcc --version | head -n 1
gcc (Debian 11.2.0-16) 11.2.0
```

Is this an expected deficiency, or something to be looked into?

### LINKED ISSUE #1180: inheritance from outer feature results in call targets not found
This small example
```
a is
  n => "a"
  b is
    q => say n
  c b is b
h : a is
  redef n => "h"

x => h.c

m => x.q
m
```
works when interpreted
```
 > ./build/bin/fz m.fz
h
```
and does not build when compiled
```
 > ./build/bin/fz -c m.fz 

error 1: NYI: in m no targets for Call to a.b.q target UNIT

one error.
```

### PR DESCRIPTION
**Pull request by fridis**
This is a large patch to fix the handling of outer types. 

Please check the individual commits, they have been done carefully to ensure the code works after each individual commit. All but the last commit do preparative restructuring of the code to simplify the actual semantic change in the last commit.

### CODE REVIEW

File: src/dev/flang/ast/AbstractFeature.java [hunk 1]
```diff
@@ -1440,6 +1440,17 @@ public AbstractType[] argTypes()
   public abstract AbstractFeature outerRef();
 
 
+  /**
+   * Is thie feature marked with the `fixed` modifier. If so, this feature is
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/AbstractFeature.java:1510]: Is this feature

**Review by michaellilltokiwa — APPROVED** [review]
