### PR TITLE
parser: do not parse single dot as operator

### LINKED ISSUE #2515: Partial call `.f` parsed incorrectly if part of an operator expression
This small example using `infix |->` as an alias for `map`
```
# infix |-> as alternative to Sequence.map
Sequence.infix |-> (f T->B) => map f

say (0..10 |-> .as_f64)
```
produces an error if the right expression is a partial dot-call:
```
 > ./build/bin/fz dotInfix.fz

dotInfix.fz:4:17: error 1: Could not find called feature
say (0..10 |-> .as_f64)
----------------^^^^^^
Feature not found: 'as_f64' (no arguments)
Target feature: 'universe'
In call: 'as_f64'

one error.
```
Apparently, the `.as_f64` is parsed as `as_f64.prefix .`.
While using parentheses
```
# infix |-> as alternative to Sequence.map
Sequence.infix |-> (f T->B) => map f

say (0..10 |-> (.as_f64))
```
fixes this
```
 > ./build/bin/fz dotInfix2.fz
[0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
```
The original code without parentheses should also work, a single dot should probably never be parsed as an operator.

### LINKED ISSUE #3678: Single dot `.` should not be parsed as `infix`/`prefix`/`postfix` operator
This code produces an error
```
 > ./build/bin/fz -e 'x => 42 |> .as_string |> say'

command line:1:12: error 1: Could not find called feature
x => 42 |> .as_string |> say

Feature not found: 'infix .' (one argument)
Target feature: 'i32'
In call: '.'

one error.

```
It should maybe behave like this
```
 > ./build/bin/fz -e 'x => 42 |> (.as_string) |> say'
42
```
Multiple dots like `..` should, however, be permitted as operators.

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #3678 
fixes #2515

### CODE REVIEW

File: src/dev/flang/parser/Parser.java [hunk 1]
```diff
@@ -2244,16 +2244,25 @@ boolean isTermPrefix()
   /**
    * Parse op
    *
-op          : OPERATOR
+op          : dot call
+            | OPERATOR
             ;
    */
-  Operator op()
+  Object op()
```
Comment (michaellilltokiwa) [inline src/dev/flang/parser/Parser.java:2251]: Should I rename `op` to `dotCallOrOp`?
