### PR TITLE
fe: fix assigning lambda to field without type. #1352

### LINKED ISSUE #1352: check-condition failed: dev.flang.ast.Feature:resultType:2220
```
ex =>

  for i in 0..10 do
    c := () ->
      say "hello"
```
```
error 1: java.lang.Error: check-condition failed: dev.flang.ast.Feature:resultType:2220
	at dev.flang.util.ANY.check(ANY.java:383)
	at dev.flang.ast.Feature.resultType(Feature.java:2220)
	at dev.flang.ast.AbstractAssign.propagateExpectedType(AbstractAssign.java:197)
	at dev.flang.ast.Feature$5.action(Feature.java:1671)
	at dev.flang.ast.AbstractAssign.visit(AbstractAssign.java:127)
	at dev.flang.ast.Feature$9.visit(Feature.java:1928)
	at dev.flang.ast.Feature$9.visit(Feature.java:1906)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:337)
	at dev.flang.ast.Feature.visit(Feature.java:1027)
	at dev.flang.ast.Feature.typeInference(Feature.java:1670)
	at dev.flang.ast.Feature.typeInference(Feature.java:1636)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:385)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:264)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:180)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:734)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.
```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #1352

### CODE REVIEW

File: src/dev/flang/ast/Feature.java [hunk 1]
```diff
@@ -1637,7 +1637,12 @@ void typeInference(Resolution res)
           }
         choiceTypeCheckAndInternalFields(res);
 
-        _resultType = resultType();
+        _resultType = resultTypeRaw();
+        if (_resultType == null)
+          {
+            AstErrors.missingResultTypeForField(this);
+            _resultType = Types.t_ERROR;
+          }
```
Comment (fridis) [inline src/dev/flang/ast/Feature.java:1645]: I have the impression that `AstErrors.missingResultTypeForField()` could be called for a non-field feature as well, resulting in a precondition failure in `missingResultTypeForField`.

Also, this ensures that `_resultType != null`, so the if inline 1650 is redundant.

File: tests/reg_issue1352/issue_1352.fz [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+#
+#  Tokiwa Software GmbH, Germany
+#
+#  Source code of Fuzion test issue_1352
+#
+# -----------------------------------------------------------------------
+
+issue_1352 =>
+  c := () ->
+    say "hello"
```
Comment (fridis) [inline tests/reg_issue1352/issue_1352.fz:26]: This example is IMHO too small, in particular, enhanced type inference could determine the type of this field (`Function unit`) without much problem, while 
```
d := a -> a.x
```
cannot.

**Review by fridis — CHANGES_REQUESTED** [review]
Good, just some minor requests for improvements.

File: tests/reg_issue1352/issue_1352.fz (hunk 2 above)
Comment (michaellilltokiwa) [reply tests/reg_issue1352/issue_1352.fz:26]: Hmm, yes that is a good point but expected_err would then change and hence we would notice. Isn't this sufficient?

Comment (fridis) [reply tests/reg_issue1352/issue_1352.fz]: Sorry for a bit more nitpicking:

You have changed the tests to do
```
  a := () -> a.x
```
which is not what I meant. With slightly improved type inference, the type of any lamdba without arguments could e inferred, so `() -> ...` is not a good example, while `a -> ...a...` is better since the a new variable `a` is introduced whose type is unknown. So the example should IMHO be something like
```
  d := a -> a.x
```
or
```
  d := a,b -> a*b
```

Comment (michaellilltokiwa) [reply tests/reg_issue1352/issue_1352.fz]: May thought was `a` can not be inferred even with better type inference because it basically returns itself and hence would need to be known already to be inferred.

**Review by fridis — APPROVED** [review]
