### PR TITLE
fuir: remove manual stack cleanup

### LINKED ISSUE #1875: FUIR stack should be empty at end of each basic block
The FUIR code uses a stack with the constraint that all values within a stack are used at the end of a basic block, values passed between basic blocks are passed via fields.  This constraint, however, is not always met at the moment, which needs to be fixed.

### LINKED ISSUE #2345: AoC issue: Small example using recursion, type inference and `panic`crashes with empty stack
This code
```
_ := n
n => if true then n else panic "n"
```
crashes `fz`
```
 > ./build//bin/fz test_empty_stack.fz

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:380)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:619)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:1126)
	at dev.flang.be.jvm.JVM.code(JVM.java:843)
	at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:465)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:817)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:810)
	at dev.flang.be.jvm.JVM.compile(JVM.java:795)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:557)
```

### LINKED ISSUE #3521: JVM backend results in `check` failure for unreachable code
Try this
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -e 'a => if false then _ := "$unit"' 

error 1: java.lang.Error: check-condition failed: CodeGen.java:198 "(v.type()                instanceof PrimitiveType pt && pt == _types.resultType(type) || v.type()                instanceof ClassType     jt && _types.resultType(type) instanceof ClassType     ct && (_fuir.clazzIsRef(type) /* we do not check exact reference assignability here */ || jt.sameAs(ct)          /* but value or choice types must be the same!        */ || jt == NULL_TYPE));"
	at dev.flang.util.ANY.check(ANY.java:439)
	at dev.flang.be.jvm.CodeGen.drop(CodeGen.java:198)
	at dev.flang.be.jvm.CodeGen.drop(CodeGen.java:55)
	at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:526)
	at dev.flang.be.jvm.Choices.match(Choices.java:487)
	at dev.flang.be.jvm.CodeGen.match(CodeGen.java:925)
	at dev.flang.be.jvm.CodeGen.match(CodeGen.java:55)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:638)
	at dev.flang.fuir.analysis.AbstractInterpreter.processCode(AbstractInterpreter.java:505)
	at dev.flang.fuir.analysis.AbstractInterpreter.processClazz(AbstractInterpreter.java:481)
	at dev.flang.be.jvm.JVM.codeForRoutine(JVM.java:1245)
	at dev.flang.be.jvm.JVM.code(JVM.java:956)
	at dev.flang.be.jvm.JVM$CompilePhase$3.compile(JVM.java:460)
	at dev.flang.be.jvm.JVM.lambda$createCode$0(JVM.java:932)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.jvm.JVM.createCode(JVM.java:925)
	at dev.flang.be.jvm.JVM.compile(JVM.java:912)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:191)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:507)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$4(Fuzion.java:1071)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:142)
	at dev.flang.util.Errors.runAndExit(Errors.java:865)
	at dev.flang.tools.Tool.run(Tool.java:142)
	at dev.flang.tools.Fuzion.main(Fuzion.java:626)


*** fatal errors encountered, stopping.
one error.
```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #1875
fixes #2345 
fixes #3521

### CODE REVIEW

**Review by fridis — COMMENTED** [review]
I am a bit confused about this. 

Looks to me as if this is a cleanup fix for #1875 that introduces bug #3649.  If so, I would prefer not to do the cleanup, but probably I have misunderstood what is happening... so please explain!

File: src/dev/flang/fuir/analysis/AbstractInterpreter.java [hunk 1]
```diff
@@ -521,27 +522,20 @@ public Pair<VALUE,RESULT> processCode(int s0)
...
-        // (tests/reg_issue1294) where this is not the case that need to be
-        // fixed, the FUIR code should contain a POP instructions to avoid this
-        // special handling here!
-        //
-        var e = _fuir.codeAt(last_s);
-        switch (e)
+    // FUIR has the (so far undocumented) invariant that the stack must be
+    // empty at the end of a basic block.
+    if (POSTCONDITIONS) ensure
+      (containsVoid(stack) || stack.isEmpty() || _fuir.alwaysResultsInVoid(last_s));
```
Comment (fridis) [inline src/dev/flang/fuir/analysis/AbstractInterpreter.java:528]: This should be

```suggestion
    if (CHECKS) check
      (containsVoid(stack) || stack.isEmpty() || _fuir.alwaysResultsInVoid(last_s));
```

**Review by fridis — APPROVED** [review]
Just a small change request: A postcondition must be at the end of a method, otherwise it is a check. See comment in the sources.
