### PR TITLE
lexer: use `codePointAt` in `raw` method

### LINKED ISSUE #1379: String literal at EOF causes error
See this: 

```
 > echo -n "e => \"\"" | PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz -

error 1: java.lang.Error: require-condition2 failed: dev.flang.util.SourceFile:codePoint:643
	at dev.flang.util.ANY.require(ANY.java:94)
	at dev.flang.util.SourceFile.codePoint(SourceFile.java:643)
	at dev.flang.parser.Lexer$StringLexer.lambda$raw$0(Lexer.java:2464)
	at java.base/java.util.Optional.map(Optional.java:260)
	at dev.flang.parser.Lexer$StringLexer.raw(Lexer.java:2464)
	at dev.flang.parser.Lexer$StringLexer.iterateCodePoints(Lexer.java:2550)
	at dev.flang.parser.Lexer$StringLexer.<init>(Lexer.java:2436)
	at dev.flang.parser.Lexer.string(Lexer.java:2897)
	at dev.flang.parser.Parser.lambda$stringTerm$12(Parser.java:2184)
	at dev.flang.parser.Lexer.relaxLineAndSpaceLimit(Lexer.java:729)
	at dev.flang.parser.Parser.stringTerm(Parser.java:2179)
	at dev.flang.parser.Parser.term(Parser.java:2133)
	at dev.flang.parser.Parser.opTail(Parser.java:1863)
	at dev.flang.parser.Parser.opExpr(Parser.java:1843)
	at dev.flang.parser.Parser.expr(Parser.java:1798)
	at dev.flang.parser.Parser.stmnt(Parser.java:2734)
	at dev.flang.parser.Parser.stmnts(Parser.java:2577)
	at dev.flang.parser.Parser.block(Parser.java:2499)
	at dev.flang.parser.Parser.implRout(Parser.java:3538)
	at dev.flang.parser.Parser.implFldOrRout(Parser.java:3566)
	at dev.flang.parser.Parser.routOrField(Parser.java:292)
	at dev.flang.parser.Parser.feature(Parser.java:253)
	at dev.flang.parser.Parser.stmnt(Parser.java:2734)
	at dev.flang.parser.Parser.stmnts(Parser.java:2577)
	at dev.flang.parser.Parser.unit(Parser.java:190)
	at dev.flang.fe.SourceModule.parseFile(SourceModule.java:203)
	at dev.flang.fe.SourceModule.parseMain(SourceModule.java:175)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:261)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:180)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:830)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)


*** fatal errors encountered, stopping.

```

### PR DESCRIPTION
**Pull request by maxteufel**
This fixes an issue where a string literal at the end of file caused an error. The problem is that the string literal is read twice, the second time it accesses the codepoints explicitly, including the character after the closing quote. This did not return an END_OF_FILE codepoint until now, instead causing a precondition failure.

Fixes #1379.

### CODE REVIEW

File: src/dev/flang/util/SourceFile.java [hunk 1]
```diff
@@ -640,10 +640,19 @@ private int[] lines()
   public int codePoint(int pos)
   {
     if (PRECONDITIONS) require
-      (pos >= 0,
-       pos < _bytes.length);
+      (pos >= 0);
```
Comment (michaellilltokiwa) [inline src/dev/flang/util/SourceFile.java:643]: It might be better fail fast here. What I mean is to keep and relax the precondition `pos < _bytes.length` to `pos <= _bytes.length`. This will make it easier to find bugs where `codePoint` is called with pos greater than `bytes.length`.

**Review by michaellilltokiwa — APPROVED** [review]
