### PR TITLE
parser: fix parsing `_ := id (Sequence i32) [ ]`

### LINKED ISSUE #6983: `[ ]` cannot be parsed
Try this
```
_ := id (Sequence i32) [ 1 , 2 , 3 ]
_ := id (Sequence i32) [ 1 , 2 ]
_ := id (Sequence i32) [ 1 ]
_ := id (Sequence i32) [ ]
```
which produces an error
```
 > /home/fridi/fuzion/work/build/bin/fz test_brackets.fz

/home/fridi/fuzion/work/test_brackets.fz:4:26: error 1: Syntax error: expected term (lbrace, lparen, lbracket, fun, string, integer, old, match, or name), found right bracket ']'
_ := id (Sequence i32) [ ]

While parsing: term, parse stack: term, opExpr, operatorExpr, inlineArray, bracketTerm, term, opExpr, operatorExpr, actualSpace, actualSpaces, actualArgs, call, call0, callOrFeatOrThis, term, opExpr, operatorExpr, implFldInit, implFldOrRout, routOrField, feature, expr, exprs, block (twice), unit

one error.
```
while removing the space in `[ ]`
```
_ := id (Sequence i32) [ 1 , 2 , 3 ]
_ := id (Sequence i32) [ 1 , 2 ]
_ := id (Sequence i32) [ 1 ]
_ := id (Sequence i32) []
```
fixes the the problem
```
 > /home/fridi/fuzion/work/build/bin/fz test_brackets2.fz
 >
```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
In case left and right brace where separated by at least one whitespace, parser tried to parse `]` as another operatorExpr.

fixes #6983

### CODE REVIEW

File: src/dev/flang/parser/Parser.java [hunk 1]
```diff
@@ -2075,25 +2075,28 @@ Expr inlineArray()
...
+                                elements.add(operatorExpr());
+                              }
+                            s = current();
+                            if ((s == Token.t_comma || s == Token.t_semicolon) && s != sep && !reportedMixed)
+                              {
+                                AstErrors.arrayInitCommaAndSemiMixed(pos, sourcePos(p1), tokenSourcePos());
+                                reportedMixed = true;
+                              }
+                          }
+                        return Void.TYPE;
```
Comment (fridis) [inline src/dev/flang/parser/Parser.java:2099]: I am myself not sure if I prefer the following code, has the same length but one call less to `operatorExpr()`:

```suggestion
                        var sep = Token.t_undefined;              // separator in use t_comma or t_semicolon
                        var sep1 = SourcePosition.notAvailable;  // position of first separator
                        do
                          {
                            if (current() != Token.t_rbracket)
                              {
                                elements.add(operatorExpr());
                              }
                            var s = current();
                            if (sep == Token.t_undefined)
                              {
                                sep = s;
                                sep1 = tokenPos();
                              }
                            else if ((s == Token.t_comma || s == Token.t_semicolon) && s != sep && sep != Token.t_error)
                              {
                                AstErrors.arrayInitCommaAndSemiMixed(pos, sourcePos(sep1), tokenSourcePos());
                                sep = Token.t_error;
                              }
                          }
                        while ((s == Token.t_comma || s == Token.t_semicolon) && skip(s))
                        return Void.TYPE;
```

**Review by fridis — APPROVED** [review]
Good. 

I tried to simplify the code, but I am unsure if I was successful. Take my version if you think so, or stick with yours if you don't.

File: src/dev/flang/parser/Parser.java (hunk 1 above)
Comment (fridis) [inline src/dev/flang/parser/Parser.java:2099]: or maybe this
```suggestion
                        var sep = Token.t_undefined;              // separator in use t_comma or t_semicolon
                        var sep1 = SourcePosition.notAvailable;  // position of first separator
                        while (current() != Token.t_rbracket && (sep == Types.t_undefined || skip(Token.t_comma) || skip(Token.t_semicolon))
                          {
                            elements.add(operatorExpr());
                            var s = current();
                            if (sep == Token.t_undefined)
                              {
                                sep = s;
                                sep1 = tokenPos();
                              }
                            else if ((s == Token.t_comma || s == Token.t_semicolon) && s != sep && sep != Token.t_error)
                              {
                                AstErrors.arrayInitCommaAndSemiMixed(pos, sourcePos(sep1), tokenSourcePos());
                                sep = Token.t_error;
                              }
                          }
                        return Void.TYPE;
```
