### PR TITLE
fe: Permit all calls with `void` as the target type, fix #1724.

### LINKED ISSUE #1724: Call on `void` target results in errors
```
x(a void) => a.asfas
x (panic "hi")
```
```
 > PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz test_args5.fz 

error 1: java.lang.Error: require-condition3 failed: dev.flang.ast.AbstractType:isAssignableFrom:304
	at dev.flang.util.ANY.require(ANY.java:113)
	at dev.flang.ast.AbstractType.isAssignableFrom(AbstractType.java:304)
	at dev.flang.ast.AbstractType.isAssignableFrom(AbstractType.java:255)
	at dev.flang.fe.SourceModule.checkTypes(SourceModule.java:1273)
	at dev.flang.ast.Feature.checkTypes(Feature.java:1700)
	at dev.flang.ast.Feature.checkTypes1and2(Feature.java:1730)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:395)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:259)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:181)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:868)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:519)


*** fatal errors encountered, stopping.
```

### PR DESCRIPTION
**Pull request by fridis**
Originally, this was required to suppress subsequent errors when type inference for formal arguments results in void. But I consider this logical (and maybe even useful) in the general case: If you have an instance of type void, you can do anything with it!

Added a test that performs different undefined calls on void.

Also removed no longer needed `Function.loadCalledFeature`, this was used only for `fun`-calls that are no longer supported.

### CODE REVIEW

File: src/dev/flang/ast/Call.java [hunk 1]
```diff
@@ -2102,7 +2135,20 @@ public Call resolveTypes(Resolution res, AbstractFeature outer)
         return this;
       }
     _resolvedFor = outer;
-    loadCalledFeature(res, outer);
+    if (!loadCalledFeatureUnlessTargetVoid(res, outer))
+      { // target of this call results in `void`, so we replace this call by the
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/Call.java:2139]: is `void`

**Review by michaellilltokiwa — APPROVED** [review]

File: src/dev/flang/ast/Call.java (hunk 1 above)
Comment (fridis) [reply src/dev/flang/ast/Call.java:2139]: I think you misread the comment...
