### PR TITLE
ast: fix "Empty Stack during DFA"

### LINKED ISSUE #2242: java.lang.Error: require-condition1 failed: dev.flang.fuir.analysis.AbstractInterpreter:pop
```
quicksort_marray =>

  # NYI this is broken currently

  print(T type, arr Mutable_Array T) =>
    for x in arr do
      yak "$x, "
    say

  partition(T type : property.orderable, arr Mutable_Array T, low i32, high i32) =>

    swap(x i32, y i32)
      =>
      tmp := arr[x]
      arr[x] := arr[y]
      arr[y] := tmp

    pivot := arr[high]
    i := mut (low - 1)
    for j in low..(high- 1) do
      if (arr[j] < pivot)
        i <- (i.get + 1)
        if i.get != j
          swap i.get j
    swap (i.get + 1) high
    (i.get + 1)

  quick_sort(T type : property.orderable, arr Mutable_Array T, low i32, high i32) =>
    if (low < high)
      pi := partition T arr low high
      quick_sort arr low (pi - 1)
      quick_sort arr (pi + 1) high

  mi : mutate is
  mi.go ()->

    a := (mutate.array f64).type.new mi 10 0.0
    for i in a.indices do
      a[i] := random.next_f64


    say "unsorted"
    print a

    quick_sort a 0 (a.count - 1)

    say "sorted"
    print a

```
```

error 1: java.lang.Error: require-condition1 failed: dev.flang.fuir.analysis.AbstractInterpreter:pop:376
        at dev.flang.util.ANY.require(ANY.java:93)
        at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:376)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:619)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA.lambda$static$258(DFA.java:1719)
        at dev.flang.fuir.analysis.dfa.Call.result(Call.java:208)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:392)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:391)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:337)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:298)
        at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:290)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:256)
        at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:83)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
        at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
        at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1087)
        at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2042)
        at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2004)
        at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:990)
        at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:849)
        at dev.flang.be.jvm.JVM.<init>(JVM.java:750)
        at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
        at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
        at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
        at dev.flang.util.Errors.runAndExit(Errors.java:790)
        at dev.flang.tools.Tool.run(Tool.java:145)
        at dev.flang.tools.Fuzion.main(Fuzion.java:557)


*** fatal errors encountered, stopping.

```

### LINKED ISSUE #2381: AoC issue: Empty Stack during DFA
This
```
dec16_part1 is

  input := (io.stdin.with ()->io.buffered.read_lines).val.filter !=""
                                                     .map (.as_codepoints)
  area := array2 String input.count input[0].count i,j->input[i][j]

  part1 =>
    lm : mutate.
    lm.go ()->
      visited := (lm.array i32).type.new lm area.length 0
      r => 1
      l => 2
      u => 4
      d => 8
      ix(x,y) => y+x*area.length1
      trace(x,y,w i32) =>
        if ((x ∈ area.indices1) &&
            (y ∈ area.indices0) &&
            (visited[ix x y] & d) = 0) then
          visited[ix x y] := visited[ix x y] | d
          c := area[y,x]
          if  w = r  &&  c = "."              then trace x+1 y   w
          if  w = l  &&  c = "."              then trace x-1 y   w
          if  w = u  &&  c = "."              then trace x   y-1 w
          if  w = d  &&  c = "."              then trace x   y+1 w
          if  w = r  &&  c = "-"              then trace x+1 y   w
          if  w = l  &&  c = "-"              then trace x-1 y   w
          if  w = u  &&  c = "|"              then trace x   y-1 w
          if  w = d  &&  c = "|"              then trace x   y+1 w
          if (w = r) && (c = "/"  || c = "|") then trace x   y-1 u
          if (w = r) && (c = "\\" || c = "|") then trace x   y+1 d
          if (w = l) && (c = "/"  || c = "|") then trace x   y-1 d
          if (w = l) && (c = "\\" || c = "|") then trace x   y+1 u
          if (w = u) && (c = "/"  || c = "-") then trace x-1 y   l
          if (w = u) && (c = "\\" || c = "-") then trace x+1 y   r
          if (w = d) && (c = "/"  || c = "-") then trace x-1 y   l
          if (w = d) && (c = "\\" || c = "-") then trace x+1 y   r
      trace 0 0 r
      (visited.filter !=0).count

  say "part1 $part1"
```
results in
```
 > ~/fuzion/clean/fuzion/build/bin/fz part1_empty_stack_exc.fz 

error 1: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at dev.flang.fuir.analysis.AbstractInterpreter.pop(AbstractInterpreter.java:380)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:619)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1178)
	at dev.flang.fuir.analysis.dfa.DFA.analyzeNewCall(DFA.java:2054)
	at dev.flang.fuir.analysis.dfa.DFA.newCall(DFA.java:2016)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call0(DFA.java:392)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access0(DFA.java:338)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.lambda$access$1(DFA.java:299)
	at dev.flang.fuir.analysis.dfa.Value.forAll(Value.java:352)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.access(DFA.java:291)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:257)
	at dev.flang.fuir.analysis.dfa.DFA$Analyze.call(DFA.java:84)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:654)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:515)
	at dev.flang.fuir.analysis.AbstractInterpreter.process(AbstractInterpreter.java:478)
	at dev.flang.fuir.analysis.dfa.DFA.analyze(DFA.java:1178)
	at dev.flang.fuir.analysis.dfa.DFA.iteration(DFA.java:1143)
	at dev.flang.fuir.analysis.dfa.DFA.findFixPoint(DFA.java:1106)
	at dev.flang.fuir.analysis.dfa.DFA.dfa(DFA.java:1088)
	at dev.flang.fuir.analysis.dfa.DFA.new_fuir(DFA.java:940)
	at dev.flang.be.jvm.JVM.<init>(JVM.java:762)
	at dev.flang.tools.Fuzion$Backend$3.process(Fuzion.java:163)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:444)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:908)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:145)
	at dev.flang.util.Errors.runAndExit(Errors.java:790)
	at dev.flang.tools.Tool.run(Tool.java:145)
	at dev.flang.tools.Fuzion.main(Fuzion.java:557)


```

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
fixes #2381
fixes #2242

I found two issues here:
- First `trace` was wrongly inferred to result in void. This was the case because Expr.union returned void as default if no type of any exprs could be inferred. Result type should actually be unit since the ifs have default else branches resulting in `unit`.
- This then triggered the problem in the DFA which tried to assign unit to a void field.

### CODE REVIEW

File: src/dev/flang/ast/Expr.java [hunk 1]
```diff
@@ -223,41 +223,50 @@ AbstractType typeForUnion()
...
           {
+            foundType = true;
             result = result.union(et);
           }
       }
 
-    return result;
+    return foundType || assumeVoidIfUnknown
+      ? result
+      : null;
```
Comment (fridis) [inline src/dev/flang/ast/Expr.java:269]: If you cannot remove `assumeVoidIfUnknown`: I think the code would be clearer if you would introduce a second boolean variable here, e.g., 

```
    var gotResult = assumeVoidIfUnknown;
    for (var e : exprs)
      {
        var et = e.typeForInferencing();
        if (et != null)
          {
            gotResult = true;
            result = result.union(et);
          }
      }

    return result;
    return gotResult
      ? result
      : null;
```

File: src/dev/flang/ast/Match.java [hunk 2]
```diff
@@ -241,6 +241,9 @@ Match assignToField(Resolution res, AbstractFeature outer, Feature r)
    */
   public Expr propagateExpectedType(Resolution res, AbstractFeature outer, AbstractType t)
   {
+    if (CHECKS) check
+      (!t.isVoid() || type().isVoid());
```
Comment (fridis) [inline src/dev/flang/ast/Match.java:245]: I fear this might introduce check failures if you do things like
```
  a(v void) =>
  b(a Any) =>
  v choice unit := unit
  a (match v
       unit => panic "bla")
  a (match v
       unit => 4711)
  b (match v
       unit => panic "bla")
  b (match v
       unit => 4711)
```

**Review by fridis — CHANGES_REQUESTED** [review]
Looks good!

I am trying to find a way to not introduce the  `assumeVoidIfUnknown` argument and I fear one `check` might be triggerred to fail, but I might be wrong.

File: tests/reg_issue662_match_cases_missing/issue662.fz.expected_err [hunk 3]
```diff
@@ -7,4 +7,10 @@ Match expression at --CURDIR--/issue662.fz:30:3:
...
 To solve this, add a case.  If a case exists, check that the indentation is deeper than that of the surrounding 'match' expression
 
-one error.
+
+--CURDIR--/issue662.fz:26:1: error 2: Failed to infer result type for feature 'issue662'.
+issue662 =>
+^^^^^^^^
+To solve this, please specify a result type explicitly.
+
+2 errors.
```
Comment (fridis) [inline tests/reg_issue662_match_cases_missing/issue662.fz.expected_err:16]: This is a subsequent error that should be suppressed. Would be good to do this within this PR.

**Review by fridis — COMMENTED** [review]
Should have flagged this before, would be good to not create a new subsequent error.

File: tests/reg_issue662_match_cases_missing/issue662.fz.expected_err (hunk 3 above)
Comment (michaellilltokiwa) [reply tests/reg_issue662_match_cases_missing/issue662.fz.expected_err:16]: @fridis Not sure what is the best approach here?

Comment (fridis) [reply tests/reg_issue662_match_cases_missing/issue662.fz.expected_err:16]: I think this could be solved by setting `_type` to `Types.t_ERROR` at the end of `Match.resolveTypes()` as follows:
```
        if (!missingMatches.isEmpty() && ok)
          {
            AstErrors.missingMatches(pos(), cgs, missingMatches);
            _type = Types.t_ERROR; 
          }
```

**Review by fridis — CHANGES_REQUESTED** [review]
Added a possible solution for the new error.

**Review by fridis — APPROVED** [review]
