### PR TITLE
fe: Fix IndexOutOfBoundsException in chained boolean, fix #1473

### LINKED ISSUE #1473: crash in chained boolean expression
This example causes `fz` to crash:
```
> echo "4 > a > b > c" | ./build/bin/fz -

-:1:5: error 1: Could not find called feature
4 > a > b > c
----^
Feature not found: 'a' (no arguments)
Target feature: 'universe'
In call: 'a'


error 2: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at dev.flang.ast.Call.findChainedBooleans(Call.java:502)
	at dev.flang.ast.Call.loadCalledFeature(Call.java:658)
	at dev.flang.ast.Call.resolveTypes(Call.java:2019)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1271)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1263)
	at dev.flang.ast.Call.visit(Call.java:1033)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:226)
	at dev.flang.ast.Block.visit(Block.java:40)
	at dev.flang.ast.Impl.visit(Impl.java:336)
	at dev.flang.ast.Feature.visit(Feature.java:1027)
	at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1309)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:371)
	at dev.flang.ast.Resolution.resolve(Resolution.java:338)
	at dev.flang.fe.SourceModule.createASTandResolve(SourceModule.java:259)
	at dev.flang.fe.FrontEnd.<init>(FrontEnd.java:181)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:843)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:748)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:494)


*** fatal errors encountered, stopping.

```

### PR DESCRIPTION
**Pull request by fridis**
To avoid complete chaos, this batch stops chained boolean conversion when any intermediate value is of error type.

For easier debugging, added `toString` to `Expr.ERROR_VALUE`.

### CODE REVIEW

File: src/dev/flang/ast/Call.java [hunk 1]
```diff
@@ -496,33 +496,34 @@ else if (_target != null)
   private void findChainedBooleans(Resolution res, AbstractFeature thiz)
   {
     var cb = chainedBoolTarget(res, thiz);
-    if (cb != null && _actuals.size() == 1)
+    if (cb != null && _actuals.size() == 1 && cb._actuals.getLast().typeIfKnown() != Types.t_ERROR)
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/Call.java:499]: `cb._actuals.getLast().typeIfKnown() != Types.t_ERROR` the same is checked in the inner `if`. So this is redundant?

Comment (fridis) [reply src/dev/flang/ast/Call.java]: I was playing around with a single `if` vs. two nested ones and finally decided for the nested `if`s and forgot to cleanup properly.
