### PR TITLE
Fix actual type generation for type feature type's type parameters, fix #1236

### LINKED ISSUE #1236: .dynamic_type leads to require-condition1 failed: dev.flang.ast.AbstractFeature:typeFeature:865
```
ex =>
  "hello".dynamic_type
```
```
error 1: java.lang.Error: require-condition1 failed: dev.flang.ast.AbstractFeature:typeFeature:865
	at dev.flang.util.ANY.require(ANY.java:78)
	at dev.flang.ast.AbstractFeature.typeFeature(AbstractFeature.java:865)
	at dev.flang.ast.AbstractType.typeType(AbstractType.java:1065)
	at dev.flang.ast.AbstractType.typeType(AbstractType.java:1039)
	at dev.flang.air.Clazz.typeClazz(Clazz.java:2043)
	at dev.flang.air.Clazz.determineResultClazz(Clazz.java:2108)
	at dev.flang.air.Clazz.dependencies(Clazz.java:415)
	at dev.flang.air.Clazzes.create(Clazzes.java:389)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1226)
	at dev.flang.air.Clazz.lookup(Clazz.java:1160)
	at dev.flang.air.Clazz.lookup(Clazz.java:1061)
	at dev.flang.air.Clazz.lookup(Clazz.java:1029)
	at dev.flang.air.Clazz.determineResultField(Clazz.java:2239)
	at dev.flang.air.Clazz.dependencies(Clazz.java:414)
	at dev.flang.air.Clazzes.create(Clazzes.java:389)
	at dev.flang.air.Clazzes.clazzWithSpecificOuter(Clazzes.java:1226)
	at dev.flang.air.Clazz.lookup(Clazz.java:1160)
	at dev.flang.air.Clazzes.findClazzes(Clazzes.java:888)
	at dev.flang.air.Clazz$1.action(Clazz.java:1428)
	at dev.flang.ast.Stmnt.visitStatements(Stmnt.java:65)
	at dev.flang.ast.AbstractCall.visitStatements(AbstractCall.java:112)
	at dev.flang.ast.Box.visitStatements(Box.java:157)
	at dev.flang.ast.AbstractAssign.visitStatements(AbstractAssign.java:140)
	at dev.flang.ast.AbstractBlock.visitStatements(AbstractBlock.java:101)
	at dev.flang.ast.AbstractFeature.visitStatements(AbstractFeature.java:1456)
	at dev.flang.air.Clazz.inspectCode(Clazz.java:1378)
	at dev.flang.air.Clazz.findAllClasses(Clazz.java:1422)
	at dev.flang.air.Clazzes.findAllClasses(Clazzes.java:456)
	at dev.flang.fuir.FUIR.<init>(FUIR.java:198)
	at dev.flang.opt.Optimizer.fuir(Optimizer.java:73)
	at dev.flang.tools.Fuzion$Backend.processFrontEnd(Fuzion.java:367)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:832)
	at dev.flang.tools.Tool.lambda$run$0(Tool.java:154)
	at dev.flang.util.Errors.runAndExit(Errors.java:704)
	at dev.flang.tools.Tool.run(Tool.java:154)
	at dev.flang.tools.Fuzion.main(Fuzion.java:481)



``

### PR DESCRIPTION
**Pull request by fridis**
See single commits for easier review. The main commit that fixes #1236 has this detail message:

Type features have an additional first type parameter, `THIS_TYPE`, and actual type parameters for the other type parameters have to be created from this. E.g., for
```
  list A
```
the type feature is
```
  list.type THIS_TYPE A
```
and the actual type of, e.g.,
```
  list.type (list (complex f32)) A
```
is
```
  list.type (list (complex f32)) (complex f32)
```
Where `A` was set to the type parameter of the actual type of `THIS_TYPE`.

Furthermore, the creation of type featurers requires types of the outer features, even if these are routines that do not define a type.  Since routines can be overloaded with different argument counts, we add the argument count to create a unique type name (that is used, e.g., in the C backend to create type names).

### CODE REVIEW

File: src/dev/flang/ast/AbstractType.java [hunk 1]
```diff
@@ -653,6 +654,16 @@ public AbstractType actualType(AbstractFeature f, List<AbstractType> actualGener
   }
 
 
+  /**
+   * Is this the type of a type feature, e.g., the type of `(list
+   * i32).type`. false is this is unknown since type was not resolved yet.
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/AbstractType.java:659]: I find this comment to be misleading since `false` can also mean that it is actually known to not be the type of a type feature.

File: src/dev/flang/ast/Type.java [hunk 2]
```diff
@@ -1061,6 +1069,19 @@ public AbstractFeature featureOfType()
   }
 
 
+  /**
+   * Is this the type of a type feature, e.g., the type of `(list
+   * i32).type`. false is this is unknown since type was not resolved yet.
```
Comment (michaellilltokiwa) [inline src/dev/flang/ast/Type.java:1074]: I find this comment to be misleading since `false` can also mean that it is actually known to not be the type of a type feature.

File: tests/reg_issue1236/issue1236.fz [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+#
+#  Tokiwa Software GmbH, Germany
+#
+#  Source code of Fuzion issue1236
+#
+#  Author: Fridtjof Siebert (siebert@tokiwa.software)
+#
+# -----------------------------------------------------------------------
+
+# simple example calling `dynamic_type?`
```
Comment (michaellilltokiwa) [inline tests/reg_issue1236/issue1236.fz:26]: What is the meaning of the question mark?

**Review by michaellilltokiwa — APPROVED** [review]

File: src/dev/flang/ast/AbstractType.java (hunk 1 above)
Comment (fridis) [reply src/dev/flang/ast/AbstractType.java:659]: Will enhance this comment. Not proud of this code that requires special handling for instances of `Type`.

File: src/dev/flang/ast/Type.java (hunk 2 above)
Comment (fridis) [reply src/dev/flang/ast/Type.java:1074]: dto.

File: tests/reg_issue1236/issue1236.fz (hunk 3 above)
Comment (fridis) [reply tests/reg_issue1236/issue1236.fz:26]: That means that my fingers are too fat...:-)
